"use client";

import { useState } from "react";
import jsPDF from "jspdf";

type AnalysisResult = {
  score: number;
  matchPercentage: number;
  summary: string;
  strengths: string[];
  missingSkills: string[];
  suggestions: string[];
};

export default function Home() {
  const [jobDescription, setJobDescription] = useState("");
  const [resumeFile, setResumeFile] = useState<File | null>(null);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const [error, setError] = useState("");

  const getMatchLabel = (score: number) => {
    if (score >= 85) return "Excellent Match";
    if (score >= 70) return "Good Match";
    if (score >= 50) return "Moderate Match";
    return "Needs Improvement";
  };

  const handleAnalyze = async () => {
    if (!resumeFile) {
      setError("Please upload your resume PDF before analyzing.");
      return;
    }

    if (!jobDescription.trim()) {
      setError("Please paste the job description before analyzing.");
      return;
    }

    setLoading(true);
    setError("");
    setResult(null);

    try {
      const formData = new FormData();
      formData.append("resume", resumeFile);
      formData.append("jobDescription", jobDescription);

      const response = await fetch("/api/analyze", {
        method: "POST",
        body: formData,
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || "Failed to analyze resume.");
      }

      setResult(data);
    } catch (err) {
      console.error(err);
      setError(
        "Unable to analyze the resume. Please check the PDF, API key, and try again."
      );
    } finally {
      setLoading(false);
    }
  };

  const downloadReport = () => {
  if (!result) return;

  const doc = new jsPDF();

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;
  let y = 20;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("CareerCraft AI", margin, y);

  y += 10;
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text("AI Resume Analysis Report", margin, y);

  y += 12;
  doc.setDrawColor(201, 162, 39);
  doc.line(margin, y, pageWidth - margin, y);

  y += 15;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text(`ATS Score: ${result.score}/100`, margin, y);

  y += 8;
  doc.text(`Match Percentage: ${result.matchPercentage}%`, margin, y);

  y += 14;
  doc.setFontSize(13);
  doc.text("AI Summary", margin, y);

  y += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  const summaryLines = doc.splitTextToSize(
    result.summary,
    pageWidth - margin * 2
  );
  doc.text(summaryLines, margin, y);
  y += summaryLines.length * 7 + 8;

  const addSection = (title: string, items: string[]) => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.text(title, margin, y);
    y += 8;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);

    items.forEach((item, index) => {
      const lines = doc.splitTextToSize(
        `${index + 1}. ${item}`,
        pageWidth - margin * 2
      );

      if (y > 270) {
        doc.addPage();
        y = 20;
      }

      doc.text(lines, margin, y);
      y += lines.length * 7;
    });

    y += 8;
  };

  addSection("Strengths", result.strengths);
  addSection("Missing Skills", result.missingSkills);
  addSection("Improvement Suggestions", result.suggestions);

  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text("Generated by CareerCraft AI", margin, 285);
  doc.text("Built by Eshitha Reddy", pageWidth - 60, 285);

  doc.save("CareerCraft_AI_Report.pdf");
};

  return (
    <main className="min-h-screen bg-[#FAF7F2] px-6 py-10 text-[#1F2937]">
      <section className="mx-auto max-w-6xl">
        <div className="rounded-[2rem] border border-[#E8DEC8] bg-white p-8 shadow-xl">
          <div className="mb-10 rounded-[1.7rem] bg-[#1F2937] px-8 py-10 text-white">
            <p className="text-sm font-semibold uppercase tracking-[0.25em] text-[#D8B84F]">
              Premium AI Resume Analyzer
            </p>

            <h1 className="mt-3 text-5xl font-bold tracking-tight">
              CareerCraft AI
            </h1>

            <p className="mt-3 flex flex-wrap items-center gap-2 text-lg">
              <span className="text-[#D8B84F]">⚡</span>
              <span className="font-semibold text-[#D8B84F]">
                Powered by AI
              </span>
              <span className="text-gray-300">
                for smarter resume analysis
              </span>
            </p>

            <p className="mt-4 max-w-2xl text-lg text-gray-200">
              Analyze your resume against any job description and get ATS score,
              missing skills, match percentage, and smart improvement
              suggestions.
            </p>

            <p className="mt-5 text-sm font-medium text-[#D8B84F]">
              Trusted by students and job seekers to improve shortlisting
              chances.
            </p>
          </div>

          <div className="grid gap-6 md:grid-cols-2">
            <div className="rounded-3xl border border-[#E8DEC8] bg-[#FFFCF7] p-6">
              <label className="text-sm font-bold uppercase tracking-wide text-[#8A6A00]">
                Upload Resume PDF
              </label>

              <p className="mt-2 text-sm text-gray-500">
                Upload your resume in PDF format.
              </p>

              <input
                type="file"
                accept=".pdf"
                onChange={(e) => {
                  setResumeFile(e.target.files?.[0] || null);
                  setError("");
                }}
                className="mt-5 w-full rounded-2xl border border-[#E8DEC8] bg-white p-4 text-gray-700"
              />

              {resumeFile && (
                <div className="mt-4 inline-flex items-center rounded-full bg-green-100 px-4 py-2 text-sm font-medium text-green-700">
                  📄 {resumeFile.name}
                </div>
              )}
            </div>

            <div className="rounded-3xl border border-[#E8DEC8] bg-[#FFFCF7] p-6">
              <label className="text-sm font-bold uppercase tracking-wide text-[#8A6A00]">
                Paste Job Description
              </label>

              <p className="mt-2 text-sm text-gray-500">
                Paste the role description to compare with your resume.
              </p>

              <textarea
                rows={9}
                value={jobDescription}
                onChange={(e) => {
                  setJobDescription(e.target.value);
                  setError("");
                }}
                placeholder="Paste the internship/job description here..."
                className="mt-5 w-full rounded-2xl border border-[#E8DEC8] bg-white p-4 text-gray-700 outline-none focus:border-[#C9A227] focus:ring-2 focus:ring-[#F3E5AB]"
              />

              <p className="mt-3 text-sm text-gray-500">
                JD Length: {jobDescription.length} characters
              </p>
            </div>
          </div>

          <button
            onClick={handleAnalyze}
            disabled={loading}
            className="mt-8 rounded-2xl bg-[#C9A227] px-8 py-4 text-lg font-bold text-white shadow-md transition hover:bg-[#B08B1E] disabled:cursor-not-allowed disabled:opacity-70"
          >
            {loading ? (
              <span className="flex items-center gap-2">
                <span className="h-5 w-5 animate-spin rounded-full border-2 border-white border-t-transparent"></span>
                AI is analyzing your resume...
              </span>
            ) : (
              "Analyze Resume"
            )}
          </button>

          {error && (
            <p className="mt-4 rounded-2xl bg-red-100 px-4 py-3 text-sm font-medium text-red-700">
              {error}
            </p>
          )}

          <div className="mt-10 grid gap-5 md:grid-cols-3">
            <div className="rounded-3xl border border-[#E8DEC8] bg-white p-6 shadow-sm">
              <p className="text-sm font-semibold text-gray-500">
                ⭐ ATS Score
              </p>

              <h3 className="mt-3 text-5xl font-bold text-[#C9A227]">
                {result ? `${result.score}/100` : "--/100"}
              </h3>

              {result && (
                <p className="mt-3 inline-block rounded-full bg-green-100 px-3 py-1 text-sm font-medium text-green-700">
                  {getMatchLabel(result.score)}
                </p>
              )}
            </div>

            <div className="rounded-3xl border border-[#E8DEC8] bg-white p-6 shadow-sm">
              <p className="text-sm font-semibold text-gray-500">
                Match Percentage
              </p>

              <h3 className="mt-3 text-3xl font-bold text-[#C9A227]">
                {result ? `${result.matchPercentage}%` : "--%"}
              </h3>

              <div className="mt-4 h-3 rounded-full bg-[#F1E8D5]">
                <div
                  className="h-3 rounded-full bg-[#C9A227] transition-all duration-700"
                  style={{
                    width: result ? `${result.matchPercentage}%` : "0%",
                  }}
                ></div>
              </div>
            </div>

            <div className="rounded-3xl border border-[#E8DEC8] bg-white p-6 shadow-sm">
              <p className="text-sm font-semibold text-gray-500">
                Missing Skills
              </p>

              <h3 className="mt-3 text-3xl font-bold text-[#C9A227]">
                {result ? result.missingSkills.length : "--"}
              </h3>
            </div>
          </div>

          <div className="mt-8 rounded-3xl border border-[#E8DEC8] bg-[#FFFCF7] p-6">
            <div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
              <h2 className="text-2xl font-bold text-[#1F2937]">
                AI Analysis Results
              </h2>

              {result && (
                <button
                  onClick={downloadReport}
                  className="rounded-2xl bg-[#1F2937] px-5 py-3 text-sm font-semibold text-white transition hover:bg-black"
                >
                  Download Report
                </button>
              )}
            </div>

            {!result && (
              <p className="mt-3 text-gray-600">
                Upload your resume and paste a job description to generate a
                detailed AI-powered analysis.
              </p>
            )}

            {result && (
              <div className="mt-5 space-y-6">
                <p className="text-sm text-gray-500">Generated just now</p>

                <div className="rounded-2xl border border-[#E8DEC8] bg-white p-5 shadow-sm">
                  <h3 className="font-bold text-[#1F2937]">AI Summary</h3>
                  <p className="mt-2 text-gray-600">{result.summary}</p>
                </div>

                <div>
                  <h3 className="mb-3 font-bold text-[#1F2937]">Strengths</h3>
                  <div className="flex flex-wrap gap-3">
                    {result.strengths.map((skill: string) => (
                      <span
                        key={skill}
                        className="rounded-full bg-green-100 px-4 py-2 text-sm font-medium text-green-700"
                      >
                        {skill}
                      </span>
                    ))}
                  </div>
                </div>

                <div>
                  <h3 className="mb-3 font-bold text-[#1F2937]">
                    Missing Skills
                  </h3>
                  <div className="flex flex-wrap gap-3">
                    {result.missingSkills.map((skill: string) => (
                      <span
                        key={skill}
                        className="rounded-full bg-red-100 px-4 py-2 text-sm font-medium text-red-700"
                      >
                        {skill}
                      </span>
                    ))}
                  </div>
                </div>

                <div>
                  <h3 className="mb-3 font-bold text-[#1F2937]">
                    Improvement Suggestions
                  </h3>
                  <div className="flex flex-wrap gap-3">
                    {result.suggestions.map((item: string) => (
                      <span
                        key={item}
                        className="rounded-full bg-[#F3E5AB] px-4 py-2 text-sm font-medium text-[#8A6A00]"
                      >
                        {item}
                      </span>
                    ))}
                  </div>
                </div>
              </div>
            )}
          </div>

          <div className="mt-8 flex flex-col gap-4 border-t border-[#E8DEC8] pt-6 text-sm text-gray-600 md:flex-row md:items-center md:justify-between">
            <p>
              Built by <strong>Eshitha Reddy</strong> ·
              eshithareddy094@gmail.com
            </p>

            <a
              href="https://digitalheroesco.com"
              target="_blank"
              className="rounded-2xl bg-[#1F2937] px-5 py-3 text-center font-semibold text-white transition hover:bg-black"
            >
              Built for Digital Heroes
            </a>
          </div>
        </div>
      </section>
    </main>
  );
}